const FETCH_TODOS = 'FETCH_TODOS';
const ADD_TODO = 'ADD_TODO';
const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
const DELETE_TODO = 'DELETE_TODO';

export {
    FETCH_TODOS,
    ADD_TODO,
    TOGGLE_CHECKED, 
    DELETE_TODO
}